CREATE TABLE "BALTUR"
(
   	"DAT" DATE DEFAULT trunc(SYSDATE) NOT NULL ENABLE,
	"DATTO" DATE DEFAULT trunc(SYSDATE) NOT NULL ENABLE,
	"ACID" CHAR(20) NOT NULL ENABLE,
	"BSAACID" CHAR(20) NOT NULL ENABLE,
	"DATL" DATE,
	"OBAC" NUMBER(19,0) DEFAULT 0 NOT NULL ENABLE,
	"OBBC" NUMBER(19,0) DEFAULT 0 NOT NULL ENABLE,
	"OBUC" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
	"DTAC" NUMBER(19,0) DEFAULT 0 NOT NULL ENABLE,
	"DTBC" NUMBER(19,0) DEFAULT 0 NOT NULL ENABLE,
	"DTUC" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
	"CTAC" NUMBER(19,0) DEFAULT 0 NOT NULL ENABLE,
	"CTBC" NUMBER(19,0) DEFAULT 0 NOT NULL ENABLE,
	"CTUC" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
	"INCL" CHAR(1) NOT NULL ENABLE,
	"CTYPE" VARCHAR2(3),
	SUPPLEMENTAL LOG DATA (ALL) COLUMNS
)

PARTITION BY RANGE ("DAT") INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
    (PARTITION "PART_BAL2_1"  VALUES LESS THAN (TO_DATE(' 2017-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) )
    ENABLE ROW MOVEMENT ;
