CREATE TABLE "BSS2"
(
	"AAC2" CHAR(5),
	"ACC2NAM" VARCHAR2(165),
	"PSAV" CHAR(1),
	"TYPE" CHAR(1),
	"ACC0" CHAR(1),
	"ACC1" CHAR(3),
	 CONSTRAINT "NN01_BSS2_AAC2" CHECK ("AAC2" is not null) ENABLE,
	 CONSTRAINT "NN01_BSS2_ACC2NAM" CHECK ("ACC2NAM" is not null) ENABLE,
	 CONSTRAINT "NN01_BSS2_PSAV" CHECK ("PSAV" is not null) ENABLE,
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
);

CREATE UNIQUE INDEX "PK01_BSS2" ON "BSS2" ("AAC2");
ALTER TABLE "BSS2" ADD CONSTRAINT "PK01_BSS2" PRIMARY KEY ("AAC2")
  USING INDEX "PK01_BSS2"  ENABLE;
