CREATE TABLE "BSS1"
(
	"ACC1" CHAR(3),
	"GRP1" CHAR(3),
	"TYPE" CHAR(1),
	"ACC0" CHAR(1),
	"PSAV" CHAR(1),
	"ACC1NAM" VARCHAR2(165),
	"GRP1NAM" VARCHAR2(165),
	CONSTRAINT "NN01_BSS1_ACC1" CHECK ("ACC1" is not null) ENABLE,
	CONSTRAINT "NN01_BSS1_GRP1" CHECK ("GRP1" is not null) ENABLE,
	CONSTRAINT "NN01_BSS1_TYPE" CHECK ("TYPE" is not null) ENABLE,
	CONSTRAINT "NN01_BSS1_ACC0" CHECK ("ACC0" is not null) ENABLE,
	CONSTRAINT "NN01_BSS1_PSAV" CHECK ("PSAV" is not null) ENABLE,
	CONSTRAINT "NN01_BSS1_ACC1NAM" CHECK ("ACC1NAM" is not null) ENABLE,
	CONSTRAINT "NN01_BSS1_GRP1NAM" CHECK ("GRP1NAM" is not null) ENABLE NOVALIDATE,
	SUPPLEMENTAL LOG DATA (ALL) COLUMNS
);
