CREATE TABLE "BSS0"
(
	"ACC0" CHAR(1),
	"TYPE" CHAR(1),
	"PSAV" CHAR(1),
	"ACC0NAM1" VARCHAR2(40),
	"ACC0NAM2" VARCHAR2(125),
	 CONSTRAINT "NN01_BSS0_ACC0" CHECK ("ACC0" is not null) ENABLE,
	 CONSTRAINT "NN01_BSS0_TYPE" CHECK ("TYPE" is not null) ENABLE,
	 CONSTRAINT "NN01_BSS0_PSAV" CHECK ("PSAV" is not null) ENABLE,
	 CONSTRAINT "NN01_BSS0_ACC0NAM1" CHECK ("ACC0NAM1" is not null) ENABLE,
	 CONSTRAINT "NN01_BSS0_ACC0NAM2" CHECK ("ACC0NAM2" is not null) ENABLE NOVALIDATE,
	 SUPPLEMENTAL LOG DATA (ALL) COLUMNS
);
