CREATE TABLE "EXCACPARM"
(
	"CCY" CHAR(3) DEFAULT '000',
	"OPTYPE" CHAR(1),
	"PSAV" CHAR(1),
	"ACC2" CHAR(5),
	"PLCODE" CHAR(5),
	"ACOD" CHAR(4),
	"ACSQ" CHAR(2),
	CONSTRAINT "NN01_EXCACPARM_CCY" CHECK ("CCY" is not null) ENABLE,
	CONSTRAINT "NN01_EXCACPARM_OPTYPE" CHECK ("OPTYPE" is not null) ENABLE,
	CONSTRAINT "NN01_EXCACPARM_PSAV" CHECK ("PSAV" is not null) ENABLE,
	CONSTRAINT "NN01_EXCACPARM_ACC2" CHECK ("ACC2" is not null) ENABLE,
	CONSTRAINT "NN01_EXCACPARM_PLCODE" CHECK ("PLCODE" is not null) ENABLE
) ;
