CREATE TABLE "EXCACRLN"
(
	"CCODE" CHAR(4),
	"CCY" CHAR(3),
	"CASH" CHAR(1),
	"PSAV" CHAR(1),
	"BSAACID" CHAR(20),
	"ACID" CHAR(20),
	"BSAACID707" CHAR(20),
	"ACID707" CHAR(20),
	 CONSTRAINT "NN01_EXCACRLN_CCODE" CHECK (CCODE IS NOT NULL ) ENABLE,
	 CONSTRAINT "NN01_EXCACRLN_PSAV" CHECK (PSAV IS NOT NULL ) ENABLE,
	 CONSTRAINT "NN01_EXCACRLN_CCY" CHECK (CCY IS NOT NULL ) ENABLE,
	 CONSTRAINT "NN01_EXCACRLN_CASH" CHECK (CASH IS NOT NULL ) ENABLE,
	 CONSTRAINT "NN01_EXCACRLN_BSAACID" CHECK ("BSAACID" is not null) ENABLE,
	 CONSTRAINT "NN01_EXCACRLN_ACID" CHECK ("ACID" is not null) ENABLE
);

CREATE UNIQUE INDEX "PK01_EXCACRLN" ON "EXCACRLN" ("CCODE", "CCY", "CASH", "PSAV");

ALTER TABLE "EXCACRLN" ADD CONSTRAINT "PK01_EXCACRLN" PRIMARY KEY ("CCODE", "CCY", "CASH", "PSAV")
	USING INDEX "PK01_EXCACRLN"  ENABLE;
