CREATE TABLE "GL_ETLPST"
(	"ID" NUMBER(22,0) NOT NULL ENABLE,
	"ID_PST" VARCHAR2(128) NOT NULL ENABLE,
	"ID_PKG" NUMBER(22,0) NOT NULL ENABLE,
	"SRC_PST" VARCHAR2(128),
	"EVT_ID" VARCHAR2(128) NOT NULL ENABLE,
	"DEAL_ID" VARCHAR2(128),
	"CHNL_NAME" VARCHAR2(128),
	"PMT_REF" VARCHAR2(128),
	"DEPT_ID" CHAR(10),
	"VDATE" DATE NOT NULL ENABLE,
	"OTS" TIMESTAMP (6) NOT NULL ENABLE,
	"NRT" VARCHAR2(300),
	"RNRTL" VARCHAR2(300),
	"RNRTS" VARCHAR2(100),
	"STRN" CHAR(1) NOT NULL ENABLE,
	"STRNRF" VARCHAR2(128),
	"AC_DR" CHAR(20),
	"CCY_DR" CHAR(3) NOT NULL ENABLE,
	"AMT_DR" NUMBER(19,3) NOT NULL ENABLE,
	"AMTRU_DR" NUMBER(19,3),
	"AC_CR" CHAR(20),
	"CCY_CR" CHAR(3) NOT NULL ENABLE,
	"AMT_CR" NUMBER(19,3) NOT NULL ENABLE,
	"AMTRU_CR" NUMBER(19,3),
	"FAN" CHAR(1) NOT NULL ENABLE,
	"PAR_RF" VARCHAR2(128),
	"ECODE" NUMBER(22,0),
	"EMSG" VARCHAR2(4000),
	"ACCKEY_DR" VARCHAR2(512),
	"ACCKEY_CR" VARCHAR2(512),
	"EVTP" VARCHAR2(20),
	"DEALID_CR" VARCHAR2(128),
	"PRFCNTR" VARCHAR2(20)
)
  PARTITION BY RANGE ("ID_PKG") INTERVAL (50000)
 (PARTITION "ETLPST_PART1"  VALUES LESS THAN (360000) )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "PK_ETLPST2" ON "GL_ETLPST" ("ID");

ALTER TABLE "GL_ETLPST" ADD CONSTRAINT "PK_ETLPST2" PRIMARY KEY ("ID")
  USING INDEX "PK_ETLPST2"  ENABLE;

  ALTER TABLE "GL_ETLPST" ADD CONSTRAINT "FK_ETLPST_PKG2" FOREIGN KEY ("ID_PKG")
	  REFERENCES "GL_ETLPKG" ("ID_PKG") ENABLE;
