CREATE TABLE "GL_POSTING"
(
  "PCID" NUMBER(22,0) NOT NULL ENABLE,
  "GLO_REF" NUMBER(22,0) NOT NULL ENABLE,
  "STRN_PCID" NUMBER(22,0),
  "POST_TYPE" CHAR(1) NOT NULL ENABLE,
  SUPPLEMENTAL LOG DATA (ALL) COLUMNS
)
PARTITION BY RANGE ("GLO_REF") INTERVAL (2000000)
  (PARTITION "POSTING_PART1"  VALUES LESS THAN (143000000));

CREATE UNIQUE INDEX "PK_PST" ON "GL_POSTING" ("PCID")
  GLOBAL PARTITION BY HASH ("PCID") ;

ALTER TABLE "GL_POSTING" ADD CONSTRAINT "PK_PST" PRIMARY KEY ("PCID")
  USING INDEX "PK_PST"  ENABLE;

ALTER TABLE "GL_POSTING" ADD CONSTRAINT "FK_POST_OPER" FOREIGN KEY ("GLO_REF")
	  REFERENCES "GL_OPER" ("GLOID") ENABLE;
