CREATE TABLE "GL_ACC_U"
(
	"ID" NUMBER(22,0),
	"BSAACID" VARCHAR2(20),
	"DATE_UPL" DATE,
	"UNF" CHAR(1) DEFAULT 'N',
	CONSTRAINT "NN01_GL_ACC_U_DATE_UPL" CHECK (DATE_UPL IS NOT NULL ) ENABLE,
	CONSTRAINT "NN01_GL_ACC_U_UNF" CHECK (UNF IS NOT NULL ) ENABLE,
	CONSTRAINT "NN01_GL_ACC_U_BSAACID" CHECK (BSAACID IS NOT NULL ) ENABLE,
	CONSTRAINT "CH_GL_ACC_U4" CHECK (BSAACID    IS NOT NULL) ENABLE,
	CONSTRAINT "NN01_GL_ACC_U_ID" CHECK ("ID" is not null) ENABLE
);

CREATE UNIQUE INDEX "PK01_GL_ACC_U" ON "GL_ACC_U" ("BSAACID");

ALTER TABLE "GL_ACC_U" ADD CONSTRAINT "PK01_GL_ACC_U" PRIMARY KEY ("BSAACID")
  USING INDEX "PK01_GL_ACC_U"  ENABLE;
