  CREATE TABLE "GL_ETLRATE"
   (	"CCY_NAME" VARCHAR2(254),
	"CCY_NOM" NUMBER(22,0),
	"MID_RATE" NUMBER(24,12),
	"CCY_NUM_CODE" VARCHAR2(10),
	"CCY_ALPHA_CODE" VARCHAR2(3),
	"ON_DATE" DATE,
	 CONSTRAINT "NN_ETLRATE_CCY_NAME" CHECK (TRIM ( CCY_NAME ) <> '' ) DISABLE,
	 CONSTRAINT "NN_ETLRATE_CCY_NOM" CHECK (TRIM ( CCY_NOM ) <> '' ) DISABLE,
	 CONSTRAINT "NN_ETLRATE_CCY_NUM_CODE" CHECK (TRIM ( CCY_NUM_CODE ) <> '' ) DISABLE,
	 CONSTRAINT "NN_ETLRATE_CCY_ACODE" CHECK (TRIM ( CCY_ALPHA_CODE ) <> '' ) DISABLE,
	 CONSTRAINT "NN01_GL_ETLRATE_CCY_NAME" CHECK ("CCY_NAME" is not null) DISABLE,
	 CONSTRAINT "NN01_GL_ETLRATE_CCY_NOM" CHECK ("CCY_NOM" is not null) DISABLE,
	 CONSTRAINT "NN01_GL_ETLRATE_MID_RATE" CHECK ("MID_RATE" is not null) ENABLE,
	 CONSTRAINT "NN01_GL_ETLRATE_CCY_NUM_CODE" CHECK ("CCY_NUM_CODE" is not null) DISABLE,
	 CONSTRAINT "NN01_GL_ETLRATE5" CHECK ("CCY_ALPHA_CODE" is not null) ENABLE,
	 CONSTRAINT "NN01_GL_ETLRATE_ON_DATE" CHECK ("ON_DATE" is not null) ENABLE
   ) ;
  CREATE UNIQUE INDEX "UN_ETLRATE" ON "GL_ETLRATE" ("CCY_ALPHA_CODE", "ON_DATE")
  ;
ALTER TABLE "GL_ETLRATE" ADD CONSTRAINT "UN_ETLRATE" UNIQUE ("CCY_ALPHA_CODE", "ON_DATE")
  USING INDEX "UN_ETLRATE"  ENABLE;
