CREATE TABLE "GL_ETLPKG"
(	"ID_PKG" NUMBER(22,0) NOT NULL ENABLE,
	"PKG_NAME" VARCHAR2(128) NOT NULL ENABLE,
	"DT_LOAD" TIMESTAMP (6) NOT NULL ENABLE,
	"STATE" VARCHAR2(64) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(512),
	"ACC_CNT" NUMBER(22,0) NOT NULL ENABLE,
	"PST_CNT" NUMBER(22,0) NOT NULL ENABLE,
	"DT_PRC" TIMESTAMP (6),
	"MESSAGE" VARCHAR2(4000),
	 CONSTRAINT "CH_ETLPKG_STATE" CHECK (STATE IN ('INPROGRESS', 'LOADED', 'WORKING', 'PROCESSED', 'ERROR', 'BUILD')) ENABLE
   )
  PARTITION BY RANGE ("DT_LOAD") INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
 (PARTITION "PART_ETLPKG1"  VALUES LESS THAN (TIMESTAMP' 2017-10-20 00:00:00') )  ENABLE ROW MOVEMENT ;
  CREATE UNIQUE INDEX "PK_ETLPKG2" ON "GL_ETLPKG" ("ID_PKG")
  ;
  CREATE UNIQUE INDEX "UN_ETLPKG2" ON "GL_ETLPKG" ("PKG_NAME")
  ;
ALTER TABLE "GL_ETLPKG" ADD CONSTRAINT "PK_ETLPKG2" PRIMARY KEY ("ID_PKG")
  USING INDEX "PK_ETLPKG2"  ENABLE;
ALTER TABLE "GL_ETLPKG" ADD CONSTRAINT "UN_ETLPKG2" UNIQUE ("PKG_NAME")
  USING INDEX "UN_ETLPKG2"  ENABLE;
