  CREATE TABLE SYS_PROP
   (
    ID_PRP VARCHAR2(30) NOT NULL,
	ID_PRN VARCHAR2(30) NOT NULL,
	REQUIRED CHAR(1) NOT NULL,
	PRPTP VARCHAR2(32) NOT NULL,
	DESCRP VARCHAR2(255) NOT NULL,
	DECIMAL_VALUE NUMBER(22,6),
	STRING_VALUE VARCHAR2(1024),
	NUMBER_VALUE NUMBER(10,0),
	BOOLEAN_VALUE VARCHAR2(5),
	 CONSTRAINT CH_SYS_PROP_REQUIRED CHECK (REQUIRED IN ( 'Y' , 'N' ) ) ,
	 CONSTRAINT CH_SYS_PROP_PRPTP CHECK (PRPTP IN ( 'DECIMAL_TYPE' , 'NUMBER_TYPE' , 'STRING_TYPE' ) ),
	 CONSTRAINT CH_SYS_PROP_BOOL CHECK (BOOLEAN_VALUE IN ( 'true' , 'false' ) )
   ) ;

CREATE UNIQUE INDEX PK01_SYS_PROP ON SYS_PROP (ID_PRP);
ALTER TABLE SYS_PROP ADD CONSTRAINT PK01_SYS_PROP PRIMARY KEY (ID_PRP) USING INDEX PK01_SYS_PROP;
