//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.08 at 01:10:04 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.sqlpatchbuilder.org/table", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.rbt.sqlmodule.parse.xjc.table;
