CREATE OR REPLACE PACKAGE aq_pkg_const IS
    C_NORMAL_QUEUE_NAME CONSTANT VARCHAR2(30) := 'BAL_QUEUE';

    C_NORMAL_QUEUE_TAB_NAME CONSTANT VARCHAR2(30) := 'BAL_QUEUE_TAB';

    C_EXCEPTION_QUEUE_NAME CONSTANT VARCHAR2(30) := 'AQ$_BAL_QUEUE_TAB_E';

    C_LOG_CODE CONSTANT VARCHAR2(30) := 'BalanceQueue';

    C_TRIGGER_FORM_ONLINE CONSTANT VARCHAR2(32) := 'ONLINE';

    C_TRIGGER_FORM_GIBRID CONSTANT VARCHAR2(32) := 'GIBRID';

    C_TRIGGER_FORM_JRN CONSTANT VARCHAR2(32) := 'JRN';

    C_TRIGGER_STATE_ENABLED CONSTANT VARCHAR2(32) := 'ENABLED';

    C_TRIGGER_STATE_DISABLED CONSTANT VARCHAR2(32) := 'DISABLED';

    C_BALANCE_QUEUE_LISTENER_PRFX CONSTANT VARCHAR2(128) := 'BALANCE_QUEUE_LISTENER';

    FUNCTION GET_CONST_TRIGGER_FORM_ONLINE RETURN VARCHAR2;

    FUNCTION GET_CONST_TRIGGER_FORM_GIBRID RETURN VARCHAR2;

    FUNCTION GET_CONST_TRIGGER_FORM_JRN RETURN VARCHAR2;

    FUNCTION GET_BALANCE_QUEUE_NAME RETURN VARCHAR2;

    FUNCTION GET_BALANCE_EXC_QUEUE_NAME RETURN VARCHAR2;

    FUNCTION GET_BALANCE_QUEUE_LISTNR_PRFX RETURN VARCHAR2;

    FUNCTION GET_QUEUE_TAB_NAME RETURN VARCHAR2;

END aq_pkg_const;
/

CREATE OR REPLACE PACKAGE BODY aq_pkg_const IS

    FUNCTION get_const_trigger_form_online RETURN VARCHAR2 IS
    BEGIN
        RETURN C_TRIGGER_FORM_ONLINE;
    END get_const_trigger_form_online;

    FUNCTION get_const_trigger_form_gibrid RETURN VARCHAR2 IS
    BEGIN
        RETURN C_TRIGGER_FORM_GIBRID;
    END get_const_trigger_form_gibrid;

    FUNCTION get_const_trigger_form_jrn RETURN VARCHAR2 IS
    BEGIN
        RETURN C_TRIGGER_FORM_JRN;
    END get_const_trigger_form_jrn;

    FUNCTION get_balance_queue_name RETURN VARCHAR2 IS
    BEGIN
        RETURN C_NORMAL_QUEUE_NAME;
    END get_balance_queue_name;

    FUNCTION get_balance_exc_queue_name RETURN VARCHAR2 IS
    BEGIN
        RETURN C_EXCEPTION_QUEUE_NAME;
    END get_balance_exc_queue_name;

    FUNCTION get_balance_queue_listnr_prfx RETURN VARCHAR2 IS
    BEGIN
        RETURN C_BALANCE_QUEUE_LISTENER_PRFX;
    END get_balance_queue_listnr_prfx;

    FUNCTION get_queue_tab_name RETURN VARCHAR2 IS
    BEGIN
        RETURN C_NORMAL_QUEUE_TAB_NAME;
    END get_queue_tab_name;

END aq_pkg_const;
/
