BEGIN
    NULL;
END;
/

SET ERRORLOGGING OFF

EXEC DBMS_OUTPUT.PUT_LINE('Checking errors...');

EXEC DBMS_UTILITY.COMPILE_SCHEMA(USER, FALSE);

COLUMN TEXT FORMAT A80

SET LINESIZE 300

-- без java warnings
SELECT * FROM USER_ERRORS WHERE TEXT NOT LIKE 'ORA-29552%' AND ATTRIBUTE <> 'WARNING' and type not like 'JAVA%' ORDER BY NAME, LINE, POSITION;

COL TIMESTAMP FORMAT A15
COL USERNAME FORMAT A15
COL SCRIPT FORMAT A10
COL IDENTIFIER FORMAT A15
COL STATEMENT FORMAT A100
COL MESSAGE FORMAT A100

--SELECT * FROM SPERRORLOG ORDER BY TIMESTAMP;

DECLARE
    L_ERRORS NUMBER(10);
BEGIN
    SELECT COUNT(1) INTO L_ERRORS FROM USER_ERRORS WHERE TEXT NOT LIKE 'ORA-29552%' AND ATTRIBUTE <> 'WARNING' and type not like 'JAVA%' ORDER BY NAME, LINE, POSITION;
    IF (L_ERRORS > 0) THEN
        RAISE_APPLICATION_ERROR(-20111, 'Errors after running the installation script: '||TO_CHAR(L_ERRORS));
    END IF;
END;
/

--DECLARE
--    L_ERRORS NUMBER(10);
--BEGIN
--    SELECT COUNT(1) INTO L_ERRORS FROM SPERRORLOG;
--    IF (L_ERRORS > 0) THEN
--        RAISE_APPLICATION_ERROR(-20111, 'SQL PLUS <SP2> errors after running the installation script: '||TO_CHAR(L_ERRORS));
--    END IF;
--END;
--/
