<#if item.exitOnError>
WHENEVER SQLERROR EXIT 1 ROLLBACK
SET ERRORLOGGING ON
</#if>

<#if item.continueOnError>
WHENEVER SQLERROR CONTINUE NONE
SET ERRORLOGGING OFF
</#if>

${body}

WHENEVER SQLERROR EXIT 1 ROLLBACK
SET ERRORLOGGING ON

