//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.03 at 07:04:59 PM MSK
//


package ru.rbt.sqlmodule.parse.xjc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DbObjectType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DbObjectType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="table"/>
 *     &lt;enumeration value="view"/>
 *     &lt;enumeration value="procedure"/>
 *     &lt;enumeration value="function"/>
 *     &lt;enumeration value="package"/>
 *     &lt;enumeration value="trigger"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DbObjectType")
@XmlEnum
public enum DbObjectType {

    @XmlEnumValue("table")
    TABLE("table"),
    @XmlEnumValue("view")
    VIEW("view"),
    @XmlEnumValue("procedure")
    PROCEDURE("procedure"),
    @XmlEnumValue("function")
    FUNCTION("function"),
    @XmlEnumValue("package")
    PACKAGE("package"),
    @XmlEnumValue("trigger")
    TRIGGER("trigger");
    private final String value;

    DbObjectType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DbObjectType fromValue(String v) {
        for (DbObjectType c: DbObjectType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
