//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.25 at 07:29:27 PM GMT+03:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.sqlpatchbuilder.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.rbt.sqlmodule.parse.xjc;
